vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /libs/images/vehicule
            upload_destination: '%kernel.project_dir%/public/libs/images/vehicule'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer