-- MySQL Script generated by MySQL Workbench
-- Fri Jul 17 10:43:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LunettesDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LunettesDb` ;

-- -----------------------------------------------------
-- Schema LunettesDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LunettesDb` DEFAULT CHARACTER SET utf8 ;
USE `LunettesDb` ;

-- -----------------------------------------------------
-- Table `LunettesDb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`user` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(150) NOT NULL,
  `prenom` VARCHAR(155) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  `cp` INT NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(125) NOT NULL,
  `telephone` VARCHAR(50) NOT NULL,
  `statut` TINYINT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`banque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`banque` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`banque` (
  `idBanque` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `statut` TINYINT NULL,
  PRIMARY KEY (`idBanque`),
  UNIQUE INDEX `idBanque_UNIQUE` (`idBanque` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`banque_has_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`banque_has_user` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`banque_has_user` (
  `banque_idBanque` INT NOT NULL,
  `user_idUser` INT NOT NULL,
  PRIMARY KEY (`banque_idBanque`, `user_idUser`),
  INDEX `fk_banque_has_user_user1_idx` (`user_idUser` ASC),
  INDEX `fk_banque_has_user_banque_idx` (`banque_idBanque` ASC),
  CONSTRAINT `fk_banque_has_user_banque`
    FOREIGN KEY (`banque_idBanque`)
    REFERENCES `LunettesDb`.`banque` (`idBanque`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_banque_has_user_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `LunettesDb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`couleur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`couleur` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`couleur` (
  `idCouleur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(155) NOT NULL,
  `statut` TINYINT NULL,
  PRIMARY KEY (`idCouleur`),
  UNIQUE INDEX `idCouleur_UNIQUE` (`idCouleur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`type` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `idType_UNIQUE` (`idType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`genre` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`genre` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `nomGenre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idGenre`),
  UNIQUE INDEX `idGenre_UNIQUE` (`idGenre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`lunettes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`lunettes` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`lunettes` (
  `idLunettes` INT NOT NULL AUTO_INCREMENT,
  `prix` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NULL,
  `quantite` INT NULL,
  `statut` TINYINT NULL,
  `couleur_idCouleur` INT NOT NULL,
  `type_idType` INT NOT NULL,
  `genre_idGenre` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  PRIMARY KEY (`idLunettes`),
  UNIQUE INDEX `idLunettes_UNIQUE` (`idLunettes` ASC),
  INDEX `fk_lunettes_couleur1_idx` (`couleur_idCouleur` ASC),
  INDEX `fk_lunettes_type1_idx` (`type_idType` ASC),
  INDEX `fk_lunettes_genre1_idx` (`genre_idGenre` ASC),
  CONSTRAINT `fk_lunettes_couleur1`
    FOREIGN KEY (`couleur_idCouleur`)
    REFERENCES `LunettesDb`.`couleur` (`idCouleur`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lunettes_type1`
    FOREIGN KEY (`type_idType`)
    REFERENCES `LunettesDb`.`type` (`idType`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lunettes_genre1`
    FOREIGN KEY (`genre_idGenre`)
    REFERENCES `LunettesDb`.`genre` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`tva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`tva` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`tva` (
  `idTva` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `statut` TINYINT NULL,
  PRIMARY KEY (`idTva`),
  UNIQUE INDEX `idTva_UNIQUE` (`idTva` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LunettesDb`.`panier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LunettesDb`.`panier` ;

CREATE TABLE IF NOT EXISTS `LunettesDb`.`panier` (
  `idPanier` INT NOT NULL AUTO_INCREMENT,
  `datePanier` DATETIME NOT NULL,
  `nomPanier` VARCHAR(255) NOT NULL,
  `quantite` INT NULL,
  `statut` TINYINT NULL,
  `user_idUser` INT NOT NULL,
  `lunettes_idLunettes` INT NOT NULL,
  `tva_idTva` INT NOT NULL,
  PRIMARY KEY (`idPanier`, `lunettes_idLunettes`, `tva_idTva`),
  UNIQUE INDEX `idPanier_UNIQUE` (`idPanier` ASC),
  INDEX `fk_panier_user1_idx` (`user_idUser` ASC),
  INDEX `fk_panier_lunettes1_idx` (`lunettes_idLunettes` ASC),
  INDEX `fk_panier_tva1_idx` (`tva_idTva` ASC),
  CONSTRAINT `fk_panier_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `LunettesDb`.`user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_panier_lunettes1`
    FOREIGN KEY (`lunettes_idLunettes`)
    REFERENCES `LunettesDb`.`lunettes` (`idLunettes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_panier_tva1`
    FOREIGN KEY (`tva_idTva`)
    REFERENCES `LunettesDb`.`tva` (`idTva`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
