-- MySQL Script generated by MySQL Workbench
-- Mon Apr 27 09:55:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retroSerie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `retroSerie` ;

-- -----------------------------------------------------
-- Schema retroSerie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retroSerie` DEFAULT CHARACTER SET utf8 ;
USE `retroSerie` ;

-- -----------------------------------------------------
-- Table `retroSerie`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`serie` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`serie` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `nomSerie` VARCHAR(125) NOT NULL,
  `AnneeSerie` INT NOT NULL,
  `paysSerie1` VARCHAR(255) NOT NULL,
  `paysSerie2` VARCHAR(255) NULL,
  `nbSaison` VARCHAR(125) NULL,
  `introSerie` LONGTEXT NOT NULL,
  `resumeSerie` LONGTEXT NOT NULL,
  `imgSerie1` VARCHAR(125) NOT NULL,
  `imgSerie2` VARCHAR(125) NOT NULL,
  `imgSerie3` VARCHAR(125) NOT NULL,
  `imgSerie4` VARCHAR(125) NOT NULL,
  `genreSerie1` VARCHAR(125) NOT NULL,
  `genreSerie2` VARCHAR(125) NULL,
  PRIMARY KEY (`idSerie`),
  UNIQUE INDEX `idSerie_UNIQUE` (`idSerie` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`user` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NOT NULL,
  `prenomUser` VARCHAR(255) NOT NULL,
  `pseudoUser` VARCHAR(125) NOT NULL,
  `maiUser` VARCHAR(125) NOT NULL,
  `telUSer` VARCHAR(125) NULL,
  `numRue` VARCHAR(125) NULL,
  `nomRue1` VARCHAR(255) NOT NULL,
  `nomRue2` VARCHAR(255) NULL,
  `cpVille` VARCHAR(125) NOT NULL,
  `nomVille` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`acteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`acteur` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`acteur` (
  `idActeur` INT NOT NULL AUTO_INCREMENT,
  `nomActeur` VARCHAR(255) NOT NULL,
  `prenomActeur` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idActeur`),
  UNIQUE INDEX `idActeur_UNIQUE` (`idActeur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`realistateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`realistateur` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`realistateur` (
  `idReal` INT NOT NULL AUTO_INCREMENT,
  `nomReal` VARCHAR(255) NOT NULL,
  `prenomReal` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idReal`),
  UNIQUE INDEX `idReal_UNIQUE` (`idReal` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
