-- MySQL Script generated by MySQL Workbench
-- Thu Apr 23 09:43:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retroSerie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema retroSerie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retroSerie` DEFAULT CHARACTER SET utf8 ;
USE `retroSerie` ;

-- -----------------------------------------------------
-- Table `retroSerie`.`serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retroSerie`.`serie` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `nomSerie` VARCHAR(125) NOT NULL,
  `AnneeSerie` INT NOT NULL,
  `paysSerie1` VARCHAR(255) NOT NULL,
  `paysSerie2` VARCHAR(255) NULL,
  `nbSaison` VARCHAR(125) NULL,
  `introSerie` LONGTEXT NOT NULL,
  `resumeSerie` LONGTEXT NOT NULL,
  `imgSerie1` VARCHAR(125) NOT NULL,
  `imgSerie2` VARCHAR(125) NOT NULL,
  `imgSerie3` VARCHAR(125) NOT NULL,
  `imgSerie4` VARCHAR(125) NOT NULL,
  `genreSerie1` VARCHAR(125) NOT NULL,
  `genreSerie2` VARCHAR(125) NULL,
  PRIMARY KEY (`idSerie`),
  UNIQUE INDEX `idSerie_UNIQUE` (`idSerie` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`typeUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retroSerie`.`typeUser` (
  `idTypeUser` INT NOT NULL AUTO_INCREMENT,
  `nomTypeUser` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeUser`),
  UNIQUE INDEX `idTypeUser_UNIQUE` (`idTypeUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retroSerie`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NOT NULL,
  `prenomUser` VARCHAR(255) NULL,
  `typeUser_idTypeUser` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_user_typeUser_idx` (`typeUser_idTypeUser` ASC),
  CONSTRAINT `fk_user_typeUser`
    FOREIGN KEY (`typeUser_idTypeUser`)
    REFERENCES `retroSerie`.`typeUser` (`idTypeUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
