<?php

namespace ContainerSRBDHQy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GnFgXiWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gnFgXiW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gnFgXiW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adresseRepository' => ['privates', 'App\\Repository\\AdresseRepository', 'getAdresseRepositoryService', true],
        ], [
            'adresseRepository' => 'App\\Repository\\AdresseRepository',
        ]);
    }
}
