<?php

namespace ContainerSRBDHQy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.22J6f42.App\Entity\Energy' shared service.
     *
     * @return \App\Entity\Energy
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.22J6f42": it references class "App\\Entity\\Energy" but no such service exists.');
    }
}
