-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 08:41:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chaussure
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `chaussure` ;

-- -----------------------------------------------------
-- Schema chaussure
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chaussure` DEFAULT CHARACTER SET utf8 ;
USE `chaussure` ;

-- -----------------------------------------------------
-- Table `chaussure`.`typeproduit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`typeproduit` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`typeproduit` (
  `idTypeProd` INT NOT NULL AUTO_INCREMENT,
  `genreProd` VARCHAR(255) NULL,
  `typeProd` VARCHAR(255) NULL,
  `matiereProd` VARCHAR(255) NULL,
  PRIMARY KEY (`idTypeProd`),
  UNIQUE INDEX `idTypeProd_UNIQUE` (`idTypeProd` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`adresse` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`adresse` (
  `idAdress` INT NOT NULL AUTO_INCREMENT,
  `numRueAdress` INT NULL,
  `intitulRueAdress` VARCHAR(255) NULL,
  `cpVilleAdress` INT NULL,
  `nomVilleAdress` VARCHAR(255) NULL,
  PRIMARY KEY (`idAdress`),
  UNIQUE INDEX `idAdress_UNIQUE` (`idAdress` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`pays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`pays` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`pays` (
  `idPays` INT NOT NULL AUTO_INCREMENT,
  `paysFabrication` VARCHAR(45) NULL,
  PRIMARY KEY (`idPays`),
  UNIQUE INDEX `idPays_UNIQUE` (`idPays` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`fournisseur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`fournisseur` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`fournisseur` (
  `idFournisseur` INT NOT NULL AUTO_INCREMENT,
  `nomFournisseur` VARCHAR(255) NULL,
  `adresse_idAdress` INT NOT NULL,
  `dateFabrication` DATE NULL,
  `stockProduit` INT NULL,
  `pays_idPays` INT NOT NULL,
  PRIMARY KEY (`idFournisseur`, `adresse_idAdress`, `pays_idPays`),
  UNIQUE INDEX `idFournisseur_UNIQUE` (`idFournisseur` ASC),
  INDEX `fk_fournisseur_adresse1_idx` (`adresse_idAdress` ASC),
  INDEX `fk_fournisseur_pays1_idx` (`pays_idPays` ASC),
  CONSTRAINT `fk_fournisseur_adresse1`
    FOREIGN KEY (`adresse_idAdress`)
    REFERENCES `chaussure`.`adresse` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fournisseur_pays1`
    FOREIGN KEY (`pays_idPays`)
    REFERENCES `chaussure`.`pays` (`idPays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`client` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nomClient` VARCHAR(255) NULL,
  `prenomClient` VARCHAR(255) NULL,
  `adresse_idAdress` INT NOT NULL,
  PRIMARY KEY (`idClient`, `adresse_idAdress`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC),
  INDEX `fk_client_adresse1_idx` (`adresse_idAdress` ASC),
  CONSTRAINT `fk_client_adresse1`
    FOREIGN KEY (`adresse_idAdress`)
    REFERENCES `chaussure`.`adresse` (`idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`genreProduit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`genreProduit` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`genreProduit` (
  `idGenreProd` INT NOT NULL AUTO_INCREMENT,
  `genreProd` VARCHAR(255) NULL,
  PRIMARY KEY (`idGenreProd`),
  UNIQUE INDEX `idGenreProd_UNIQUE` (`idGenreProd` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`produit` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`produit` (
  `idProduit` INT NOT NULL AUTO_INCREMENT,
  `nomProd` VARCHAR(255) NULL,
  `quantiteProd` VARCHAR(255) NULL,
  `pointureProd` INT NULL,
  `prixProd` DECIMAL(2) NULL,
  `dateAjoutProd` DATE NULL,
  `dateModifProd` DATE NULL,
  `typeproduit_idTypeProd` INT NOT NULL,
  `fournisseur_idFournisseur` INT NOT NULL,
  `client_idClient` INT NOT NULL,
  `client_adresse_idAdress` INT NOT NULL,
  `genreProduit_idGenreProd` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `typeproduit_idTypeProd`, `fournisseur_idFournisseur`, `client_idClient`, `client_adresse_idAdress`, `genreProduit_idGenreProd`),
  UNIQUE INDEX `idProduit_UNIQUE` (`idProduit` ASC),
  INDEX `fk_produit_typeproduit_idx` (`typeproduit_idTypeProd` ASC),
  INDEX `fk_produit_fournisseur1_idx` (`fournisseur_idFournisseur` ASC),
  INDEX `fk_produit_client1_idx` (`client_idClient` ASC, `client_adresse_idAdress` ASC),
  INDEX `fk_produit_genreProduit1_idx` (`genreProduit_idGenreProd` ASC),
  CONSTRAINT `fk_produit_typeproduit`
    FOREIGN KEY (`typeproduit_idTypeProd`)
    REFERENCES `chaussure`.`typeproduit` (`idTypeProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_fournisseur1`
    FOREIGN KEY (`fournisseur_idFournisseur`)
    REFERENCES `chaussure`.`fournisseur` (`idFournisseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_client1`
    FOREIGN KEY (`client_idClient` , `client_adresse_idAdress`)
    REFERENCES `chaussure`.`client` (`idClient` , `adresse_idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_genreProduit1`
    FOREIGN KEY (`genreProduit_idGenreProd`)
    REFERENCES `chaussure`.`genreProduit` (`idGenreProd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chaussure`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chaussure`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `chaussure`.`utilisateur` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NULL,
  `prenomUser` VARCHAR(255) NULL,
  `client_idClient` INT NOT NULL,
  `client_adresse_idAdress` INT NOT NULL,
  PRIMARY KEY (`idUser`, `client_idClient`, `client_adresse_idAdress`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_utilisateur_client1_idx` (`client_idClient` ASC, `client_adresse_idAdress` ASC),
  CONSTRAINT `fk_utilisateur_client1`
    FOREIGN KEY (`client_idClient` , `client_adresse_idAdress`)
    REFERENCES `chaussure`.`client` (`idClient` , `adresse_idAdress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
