-- MySQL Script generated by MySQL Workbench
-- Mon Mar 30 14:17:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Product
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Product` ;

-- -----------------------------------------------------
-- Schema Product
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Product` DEFAULT CHARACTER SET utf8 ;
USE `Product` ;

-- -----------------------------------------------------
-- Table `Product`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product`.`Category` ;

CREATE TABLE IF NOT EXISTS `Product`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `NomCat` VARCHAR(255) NOT NULL,
  `typeCat` VARCHAR(255) NOT NULL,
  `statutCat` INT NULL,
  `dateAddCat` DATE NOT NULL,
  `dateUpdateCat` DATE NULL,
  PRIMARY KEY (`idCategory`),
  UNIQUE INDEX `idCategory_UNIQUE` (`idCategory` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product`.`Product` ;

CREATE TABLE IF NOT EXISTS `Product`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `nomProduct` VARCHAR(255) NOT NULL,
  `prixProduct` DECIMAL UNSIGNED NOT NULL,
  `dateAjoutProduct` DATE NOT NULL,
  `dateModifProduct` DATE NULL,
  `statutProduc` INT NULL,
  `Category_idCategory` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `Category_idCategory`),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC),
  INDEX `fk_Product_Category_idx` (`Category_idCategory` ASC),
  CONSTRAINT `fk_Product_Category`
    FOREIGN KEY (`Category_idCategory`)
    REFERENCES `Product`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
