vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /libs/img/lunettes
            upload_destination: '%kernel.project_dir%/public/libs/img/lunettes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer