<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJc4Q4Ag\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJc4Q4Ag/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJc4Q4Ag.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJc4Q4Ag\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJc4Q4Ag\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jc4Q4Ag',
    'container.build_id' => '771008d5',
    'container.build_time' => 1743513985,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJc4Q4Ag');
