<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSRBDHQy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSRBDHQy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSRBDHQy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSRBDHQy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSRBDHQy\App_KernelDevDebugContainer([
    'container.build_hash' => 'SRBDHQy',
    'container.build_id' => 'ad589547',
    'container.build_time' => 1685645972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSRBDHQy');
