<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHnlqA4l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHnlqA4l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHnlqA4l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHnlqA4l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHnlqA4l\App_KernelDevDebugContainer([
    'container.build_hash' => 'HnlqA4l',
    'container.build_id' => 'a2587f82',
    'container.build_time' => 1781593011,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHnlqA4l');
