<?php

namespace ContainerJc4Q4Ag;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1KwIy0QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1KwIy0Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1KwIy0Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'option' => ['privates', '.errored..service_locator.1KwIy0Q.App\\Entity\\Options', NULL, 'Cannot autowire service ".service_locator.1KwIy0Q": it references class "App\\Entity\\Options" but no such service exists.'],
        ], [
            'option' => 'App\\Entity\\Options',
        ]);
    }
}
