<?php

namespace ContainerJc4Q4Ag;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QE3AZHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qE3A_zH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qE3A_zH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'energyRepository' => ['privates', 'App\\Repository\\EnergyRepository', 'getEnergyRepositoryService', true],
        ], [
            'energyRepository' => 'App\\Repository\\EnergyRepository',
        ]);
    }
}
