<?php

namespace ContainerJc4Q4Ag;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GQBSZDQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gQBSZDQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gQBSZDQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeVehicule' => ['privates', '.errored..service_locator.gQBSZDQ.App\\Entity\\TypeVehicule', NULL, 'Cannot autowire service ".service_locator.gQBSZDQ": it references class "App\\Entity\\TypeVehicule" but no such service exists.'],
        ], [
            'typeVehicule' => 'App\\Entity\\TypeVehicule',
        ]);
    }
}
