<?php

namespace ContainerJc4Q4Ag;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_22J6f42Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.22J6f42' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.22J6f42'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'energy' => ['privates', '.errored..service_locator.22J6f42.App\\Entity\\Energy', NULL, 'Cannot autowire service ".service_locator.22J6f42": it references class "App\\Entity\\Energy" but no such service exists.'],
        ], [
            'energy' => 'App\\Entity\\Energy',
        ]);
    }
}
