<?php

namespace ContainerJc4Q4Ag;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QQnzsFB.App\Entity\Marque' shared service.
     *
     * @return \App\Entity\Marque
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QQnzsFB": it references class "App\\Entity\\Marque" but no such service exists.');
    }
}
