-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 08:39:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maisonLoca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `maisonLoca` ;

-- -----------------------------------------------------
-- Schema maisonLoca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maisonLoca` DEFAULT CHARACTER SET utf8 ;
USE `maisonLoca` ;

-- -----------------------------------------------------
-- Table `maisonLoca`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`agence` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`agence` (
  `idAgence` INT NOT NULL AUTO_INCREMENT,
  `nomAgence` VARCHAR(255) NOT NULL,
  `emailAgence` VARCHAR(255) NULL,
  `telAgence` VARCHAR(125) NOT NULL,
  `numRueAgence` VARCHAR(45) NULL,
  `adressAgence` VARCHAR(255) NOT NULL,
  `cpAgence` VARCHAR(45) NOT NULL,
  `villeAgence` VARCHAR(125) NOT NULL,
  `statutAgence` INT(2) NOT NULL,
  PRIMARY KEY (`idAgence`),
  UNIQUE INDEX `idContact_UNIQUE` (`idAgence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`disponibilite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`disponibilite` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`disponibilite` (
  `idDispo` INT NOT NULL AUTO_INCREMENT,
  `nomDispo` VARCHAR(125) NOT NULL,
  `dateDispo` DATE NULL,
  `dateAchat` DATETIME NULL,
  PRIMARY KEY (`idDispo`),
  UNIQUE INDEX `idTypeVente_UNIQUE` (`idDispo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`bien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`bien` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`bien` (
  `idBien` INT NOT NULL AUTO_INCREMENT,
  `nomBien` VARCHAR(255) NOT NULL,
  `resumeBien` VARCHAR(255) NULL,
  `prixBien` VARCHAR(125) NOT NULL,
  `nbPiece` VARCHAR(125) NULL,
  `surfBien` VARCHAR(125) NULL,
  `surfArea` VARCHAR(125) NULL,
  `typeBien` VARCHAR(125) NOT NULL,
  `numRue` VARCHAR(125) NULL,
  `nomRue` VARCHAR(255) NOT NULL,
  `cpVille` VARCHAR(125) NOT NULL,
  `nomVille` VARCHAR(125) NOT NULL,
  `photoBien` VARCHAR(125) NULL,
  `agence_idAgence` INT NOT NULL,
  `disponibilite_idDispo` INT NOT NULL,
  PRIMARY KEY (`idBien`),
  UNIQUE INDEX `idMaison_UNIQUE` (`idBien` ASC),
  INDEX `fk_maison_agence1_idx` (`agence_idAgence` ASC),
  INDEX `fk_bien_disponibilite1_idx` (`disponibilite_idDispo` ASC),
  CONSTRAINT `fk_maison_agence1`
    FOREIGN KEY (`agence_idAgence`)
    REFERENCES `maisonLoca`.`agence` (`idAgence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bien_disponibilite1`
    FOREIGN KEY (`disponibilite_idDispo`)
    REFERENCES `maisonLoca`.`disponibilite` (`idDispo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`user` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NOT NULL,
  `prenomUser` VARCHAR(255) NOT NULL,
  `pseudoUser` VARCHAR(125) NOT NULL,
  `emailUser` VARCHAR(255) NOT NULL,
  `mdpUser` VARCHAR(125) NOT NULL,
  `adress1User` VARCHAR(255) NOT NULL,
  `adress2User` VARCHAR(255) NULL,
  `cpUser` VARCHAR(45) NOT NULL,
  `villeUser` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idContact_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`detailBien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`detailBien` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`detailBien` (
  `idDetail` INT NOT NULL AUTO_INCREMENT,
  `nomDetail` VARCHAR(125) NOT NULL,
  `avantage` VARCHAR(255) NOT NULL,
  `inconvenient` VARCHAR(255) NOT NULL,
  `etat` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idDetail`),
  UNIQUE INDEX `idDetail_UNIQUE` (`idDetail` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
