-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 15:26:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maisonLoca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `maisonLoca` ;

-- -----------------------------------------------------
-- Schema maisonLoca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maisonLoca` DEFAULT CHARACTER SET utf8 ;
USE `maisonLoca` ;

-- -----------------------------------------------------
-- Table `maisonLoca`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`type` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`type` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `nomType` VARCHAR(125) NOT NULL,
  `dateDispo` DATE NULL,
  `dateAchat` DATETIME NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `idTypeVente_UNIQUE` (`idType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`agence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`agence` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`agence` (
  `idAgence` INT NOT NULL AUTO_INCREMENT,
  `nomAgence` VARCHAR(255) NOT NULL,
  `emailAgence` VARCHAR(255) NULL,
  `adressAgence` VARCHAR(255) NOT NULL,
  `cpAgence` VARCHAR(45) NOT NULL,
  `villeAgence` VARCHAR(125) NOT NULL,
  `numRueAgence` VARCHAR(45) NULL,
  PRIMARY KEY (`idAgence`),
  UNIQUE INDEX `idContact_UNIQUE` (`idAgence` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`maison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`maison` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`maison` (
  `idMaison` INT NOT NULL AUTO_INCREMENT,
  `nomMaison` VARCHAR(255) NOT NULL,
  `resumeMaison` VARCHAR(255) NULL,
  `prixMaison` VARCHAR(125) NOT NULL,
  `nbPiece` VARCHAR(125) NULL,
  `surfMaison` VARCHAR(125) NULL,
  `surfArea` VARCHAR(125) NULL,
  `numRue` VARCHAR(125) NULL,
  `nomRue` VARCHAR(255) NOT NULL,
  `cpVille` VARCHAR(125) NOT NULL,
  `nomVille` VARCHAR(125) NOT NULL,
  `photoMaison` VARCHAR(125) NULL,
  `agence_idAgence` INT NOT NULL,
  `type_idType` INT NOT NULL,
  PRIMARY KEY (`idMaison`),
  UNIQUE INDEX `idMaison_UNIQUE` (`idMaison` ASC),
  INDEX `fk_maison_type1_idx` (`type_idType` ASC),
  INDEX `fk_maison_agence1_idx` (`agence_idAgence` ASC),
  CONSTRAINT `fk_maison_type1`
    FOREIGN KEY (`type_idType`)
    REFERENCES `maisonLoca`.`type` (`idType`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_maison_agence1`
    FOREIGN KEY (`agence_idAgence`)
    REFERENCES `maisonLoca`.`agence` (`idAgence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`contact` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`contact` (
  `idContact` INT NOT NULL AUTO_INCREMENT,
  `nomContact` VARCHAR(255) NOT NULL,
  `prenomContact` VARCHAR(255) NOT NULL,
  `emailContact` VARCHAR(255) NOT NULL,
  `adress1Contact` VARCHAR(255) NOT NULL,
  `adress2Contact` VARCHAR(255) NULL,
  `cpContact` VARCHAR(45) NOT NULL,
  `villeContact` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`idContact`),
  UNIQUE INDEX `idContact_UNIQUE` (`idContact` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`detailMaison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`detailMaison` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`detailMaison` (
  `idDetail` INT NOT NULL AUTO_INCREMENT,
  `caracteristique` LONGTEXT NOT NULL,
  `avantage` VARCHAR(255) NOT NULL,
  `inconvenient` VARCHAR(255) NOT NULL,
  `etat` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idDetail`),
  UNIQUE INDEX `idDetail_UNIQUE` (`idDetail` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
