-- MySQL Script generated by MySQL Workbench
-- Fri Apr 10 11:52:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maisonLoca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `maisonLoca` ;

-- -----------------------------------------------------
-- Schema maisonLoca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maisonLoca` DEFAULT CHARACTER SET utf8 ;
USE `maisonLoca` ;

-- -----------------------------------------------------
-- Table `maisonLoca`.`maison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`maison` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`maison` (
  `idMaison` INT NOT NULL AUTO_INCREMENT,
  `nomMaison` VARCHAR(255) NOT NULL,
  `resumeMaison` VARCHAR(255) NULL,
  `prixMaison` VARCHAR(125) NOT NULL,
  `photoMaison` VARCHAR(125) NOT NULL,
  `descMaison` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMaison`),
  UNIQUE INDEX `idMaison_UNIQUE` (`idMaison` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`contact` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`contact` (
  `idContact` INT NOT NULL AUTO_INCREMENT,
  `nomContact` VARCHAR(255) NOT NULL,
  `prenomContact` VARCHAR(255) NOT NULL,
  `emailContact` VARCHAR(255) NOT NULL,
  `adress1Contact` VARCHAR(255) NOT NULL,
  `adress2Contact` VARCHAR(255) NULL,
  `cpContact` VARCHAR(45) NOT NULL,
  `villeContact` VARCHAR(125) NOT NULL,
  `paysContact` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`idContact`),
  UNIQUE INDEX `idContact_UNIQUE` (`idContact` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`detailMaison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`detailMaison` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`detailMaison` (
  `idDetail` INT NOT NULL AUTO_INCREMENT,
  `caracteristique` LONGTEXT NOT NULL,
  `avantage` VARCHAR(255) NOT NULL,
  `inconvenient` VARCHAR(255) NOT NULL,
  `etat` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idDetail`),
  UNIQUE INDEX `idDetail_UNIQUE` (`idDetail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maisonLoca`.`typeVente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `maisonLoca`.`typeVente` ;

CREATE TABLE IF NOT EXISTS `maisonLoca`.`typeVente` (
  `idTypeVente` INT NOT NULL AUTO_INCREMENT,
  `nomType` VARCHAR(125) NOT NULL,
  `dateDispo` DATE NOT NULL,
  `dateAchat` DATETIME NOT NULL,
  `statutType` INT(2) NOT NULL,
  PRIMARY KEY (`idTypeVente`),
  UNIQUE INDEX `idTypeVente_UNIQUE` (`idTypeVente` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
