<?php

namespace ContainerHnlqA4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H944W1yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h944W1y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h944W1y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeVehiculeRepository' => ['privates', 'App\\Repository\\TypeVehiculeRepository', 'getTypeVehiculeRepositoryService', true],
        ], [
            'typeVehiculeRepository' => 'App\\Repository\\TypeVehiculeRepository',
        ]);
    }
}
