<?php

namespace ContainerHnlqA4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_54DAgsPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.54DAgsP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.54DAgsP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'energy' => ['privates', '.errored..service_locator.54DAgsP.App\\Entity\\Energy', NULL, 'Cannot autowire service ".service_locator.54DAgsP": it needs an instance of "App\\Entity\\Energy" but this type has been excluded in "config/services.yaml".'],
        ], [
            'energy' => 'App\\Entity\\Energy',
        ]);
    }
}
