<?php

namespace ContainerHnlqA4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QKB8rj1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qKB8rj1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qKB8rj1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'optionsRepository' => ['privates', 'App\\Repository\\OptionsRepository', 'getOptionsRepositoryService', true],
        ], [
            'optionsRepository' => 'App\\Repository\\OptionsRepository',
        ]);
    }
}
