<?php

namespace ContainerHnlqA4l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gy29U9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gy29U_9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gy29U_9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', '.errored.FaAISPY', NULL, 'Cannot determine controller argument for "App\\Controller\\ContactController::index()": the $mailer argument is type-hinted with the non-existent class or interface: "Swift_Mailer".'],
        ], [
            'mailer' => '?',
        ]);
    }
}
