<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TI3U7ClService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TI3U7Cl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TI3U7Cl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tvaRepository' => ['privates', 'App\\Repository\\TvaRepository', 'getTvaRepositoryService', true],
        ], [
            'tvaRepository' => 'App\\Repository\\TvaRepository',
        ]);
    }
}
