<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IErkXkIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IErkXkI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IErkXkI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lunettesRepository' => ['privates', 'App\\Repository\\LunettesRepository', 'getLunettesRepositoryService', true],
        ], [
            'lunettesRepository' => 'App\\Repository\\LunettesRepository',
        ]);
    }
}
