<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LgqXpMaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lgqXpMa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lgqXpMa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'banque' => ['privates', '.errored..service_locator.lgqXpMa.App\\Entity\\Banque', NULL, 'Cannot autowire service ".service_locator.lgqXpMa": it references class "App\\Entity\\Banque" but no such service exists.'],
        ], [
            'banque' => 'App\\Entity\\Banque',
        ]);
    }
}
