<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FIPGOsuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fIPGOsu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fIPGOsu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'couleur' => ['privates', '.errored..service_locator.fIPGOsu.App\\Entity\\Couleur', NULL, 'Cannot autowire service ".service_locator.fIPGOsu": it references class "App\\Entity\\Couleur" but no such service exists.'],
        ], [
            'couleur' => 'App\\Entity\\Couleur',
        ]);
    }
}
