<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBanqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lgqXpMa.App\Entity\Banque' shared service.
     *
     * @return \App\Entity\Banque
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.lgqXpMa": it references class "App\\Entity\\Banque" but no such service exists.');
    }
}
