<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLunettesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5kWn6mC.App\Entity\Lunettes' shared service.
     *
     * @return \App\Entity\Lunettes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5kWn6mC": it references class "App\\Entity\\Lunettes" but no such service exists.');
    }
}
