<?php

namespace ContainerJdeEKcI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTvaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5H3QkYl.App\Entity\Tva' shared service.
     *
     * @return \App\Entity\Tva
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.5H3QkYl": it references class "App\\Entity\\Tva" but no such service exists.');
    }
}
