<?php

namespace ContainerYpS05lr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QQnzsFBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QQnzsFB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QQnzsFB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'marque' => ['privates', '.errored..service_locator.QQnzsFB.App\\Entity\\Marque', NULL, 'Cannot autowire service ".service_locator.QQnzsFB": it references class "App\\Entity\\Marque" but no such service exists.'],
        ], [
            'marque' => 'App\\Entity\\Marque',
        ]);
    }
}
