<?php

namespace ContainerYpS05lr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EhLGbwCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EhLGbwC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EhLGbwC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'typeVehiculeRepository' => ['privates', 'App\\Repository\\TypeVehiculeRepository', 'getTypeVehiculeRepositoryService', true],
        ], [
            'typeVehiculeRepository' => 'App\\Repository\\TypeVehiculeRepository',
        ]);
    }
}
