<?php

namespace ContainerYpS05lr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__XEeL7HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..XEeL7H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..XEeL7H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'optionsRepository' => ['privates', 'App\\Repository\\OptionsRepository', 'getOptionsRepositoryService', true],
        ], [
            'optionsRepository' => 'App\\Repository\\OptionsRepository',
        ]);
    }
}
