<?php

namespace ContainerYpS05lr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeVehiculeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gQBSZDQ.App\Entity\TypeVehicule' shared service.
     *
     * @return \App\Entity\TypeVehicule
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gQBSZDQ": it references class "App\\Entity\\TypeVehicule" but no such service exists.');
    }
}
