-- MySQL Script generated by MySQL Workbench
-- Wed May 13 16:12:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retroSerie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `retroSerie` ;

-- -----------------------------------------------------
-- Schema retroSerie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retroSerie` DEFAULT CHARACTER SET utf8 ;
USE `retroSerie` ;

-- -----------------------------------------------------
-- Table `retroSerie`.`episode`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`episode` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`episode` (
  `idEpisode` INT NOT NULL AUTO_INCREMENT,
  `nbEpisode` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`idEpisode`),
  UNIQUE INDEX `idEpisode_UNIQUE` (`idEpisode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`saison`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`saison` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`saison` (
  `idSaison` INT NOT NULL AUTO_INCREMENT,
  `nomSaison` VARCHAR(125) NOT NULL,
  `episode_idEpisode` INT NOT NULL,
  PRIMARY KEY (`idSaison`),
  UNIQUE INDEX `idSaison_UNIQUE` (`idSaison` ASC),
  INDEX `fk_saison_episode1_idx` (`episode_idEpisode` ASC),
  CONSTRAINT `fk_saison_episode1`
    FOREIGN KEY (`episode_idEpisode`)
    REFERENCES `retroSerie`.`episode` (`idEpisode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`musique`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`musique` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`musique` (
  `idMusique` INT NOT NULL,
  `nomMusique` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMusique`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`serie` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`serie` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `imgSerie1` VARCHAR(125) NOT NULL,
  `imgSerie2` VARCHAR(125) NOT NULL,
  `imgSerie3` VARCHAR(125) NOT NULL,
  `imgSerie4` VARCHAR(125) NOT NULL,
  `saison_idSaison` INT NOT NULL,
  `musique_idMusique` INT NOT NULL,
  PRIMARY KEY (`idSerie`),
  UNIQUE INDEX `idSerie_UNIQUE` (`idSerie` ASC),
  INDEX `fk_serie_saison1_idx` (`saison_idSaison` ASC),
  INDEX `fk_serie_musique1_idx` (`musique_idMusique` ASC),
  CONSTRAINT `fk_serie_saison1`
    FOREIGN KEY (`saison_idSaison`)
    REFERENCES `retroSerie`.`saison` (`idSaison`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_serie_musique1`
    FOREIGN KEY (`musique_idMusique`)
    REFERENCES `retroSerie`.`musique` (`idMusique`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`user` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NOT NULL,
  `prenomUser` VARCHAR(255) NOT NULL,
  `pseudoUser` VARCHAR(125) NOT NULL,
  `mailUser` VARCHAR(125) NOT NULL,
  `mpdUser` VARCHAR(255) NOT NULL,
  `numRue` VARCHAR(125) NULL,
  `nomRue1` VARCHAR(255) NOT NULL,
  `nomRue2` VARCHAR(255) NULL,
  `cpVille` VARCHAR(125) NOT NULL,
  `nomVille` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`acteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`acteur` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`acteur` (
  `idActeur` INT NOT NULL AUTO_INCREMENT,
  `nomActeur` VARCHAR(255) NOT NULL,
  `prenomActeur` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idActeur`),
  UNIQUE INDEX `idActeur_UNIQUE` (`idActeur` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroSerie`.`realistateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroSerie`.`realistateur` ;

CREATE TABLE IF NOT EXISTS `retroSerie`.`realistateur` (
  `idReal` INT NOT NULL AUTO_INCREMENT,
  `nomReal` VARCHAR(255) NOT NULL,
  `prenomReal` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idReal`),
  UNIQUE INDEX `idReal_UNIQUE` (`idReal` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
