-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 14:10:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retroTv
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `retroTv` ;

-- -----------------------------------------------------
-- Schema retroTv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retroTv` DEFAULT CHARACTER SET utf8 ;
USE `retroTv` ;

-- -----------------------------------------------------
-- Table `retroTv`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroTv`.`role` ;

CREATE TABLE IF NOT EXISTS `retroTv`.`role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `nomRole` VARCHAR(125) NOT NULL,
  PRIMARY KEY (`idRole`),
  UNIQUE INDEX `idRole_UNIQUE` (`idRole` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroTv`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroTv`.`user` ;

CREATE TABLE IF NOT EXISTS `retroTv`.`user` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `nomUser` VARCHAR(255) NOT NULL,
  `prenomUser` VARCHAR(255) NOT NULL,
  `pseudoUser` VARCHAR(125) NOT NULL,
  `mailUser` VARCHAR(125) NOT NULL,
  `mdpUser` VARCHAR(255) NOT NULL,
  `numRue` VARCHAR(125) NULL,
  `nomRue1` VARCHAR(255) NOT NULL,
  `nomRue2` VARCHAR(255) NULL,
  `cpVille` VARCHAR(125) NOT NULL,
  `nomVille` VARCHAR(255) NOT NULL,
  `activate` TINYINT NOT NULL DEFAULT 1,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `retroTv`.`role` (`idRole`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroTv`.`serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroTv`.`serie` ;

CREATE TABLE IF NOT EXISTS `retroTv`.`serie` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `apiSerieId` INT NOT NULL,
  `nomSerie` VARCHAR(125) NOT NULL,
  `saisonSerie` VARCHAR(125) NULL,
  `episodeSerie` VARCHAR(125) NULL,
  UNIQUE INDEX `id_UNIQUE` (`idSerie` ASC),
  PRIMARY KEY (`idSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retroTv`.`commentaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retroTv`.`commentaire` ;

CREATE TABLE IF NOT EXISTS `retroTv`.`commentaire` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `auteurComment` VARCHAR(125) NOT NULL,
  `textComment` LONGTEXT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `dateModif` DATE NULL,
  `activate` TINYINT NULL DEFAULT 1,
  `serie_id` INT NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idCommentaire_UNIQUE` (`idComment` ASC),
  INDEX `fk_commentaire_serie1_idx` (`serie_id` ASC),
  CONSTRAINT `fk_commentaire_serie1`
    FOREIGN KEY (`serie_id`)
    REFERENCES `retroTv`.`serie` (`idSerie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
