<?php

namespace ContainerXQ7JQuT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Oo1iOtnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Oo1iOtn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Oo1iOtn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tvaRepository' => ['privates', 'App\\Repository\\TvaRepository', 'getTvaRepositoryService', true],
        ], [
            'tvaRepository' => 'App\\Repository\\TvaRepository',
        ]);
    }
}
