<?php

namespace ContainerXQ7JQuT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LemZGJlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LemZGJl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lunettesRepository' => ['privates', 'App\\Repository\\LunettesRepository', 'getLunettesRepositoryService', true],
            'mailer' => ['privates', '.errored.vpeyndY', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $mailer argument is type-hinted with the non-existent class or interface: "Swift_Mailer".'],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'em' => '?',
            'lunettesRepository' => 'App\\Repository\\LunettesRepository',
            'mailer' => '?',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.LemZGJl'])) {
            return $container->privates['.service_locator.LemZGJl'];
        }

        return $container->privates['.service_locator.LemZGJl'] = $instance;
    }
}
