<?php

namespace ContainerXQ7JQuT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RwZZDAbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rwZZDAb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'lunettesRepository' => ['privates', 'App\\Repository\\LunettesRepository', 'getLunettesRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'lunettesRepository' => 'App\\Repository\\LunettesRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.rwZZDAb'])) {
            return $container->privates['.service_locator.rwZZDAb'];
        }

        return $container->privates['.service_locator.rwZZDAb'] = $instance;
    }
}
