<?php

namespace ContainerNwY6cf3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FQCOlEZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fQCOlEZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fQCOlEZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeVehicule' => ['privates', '.errored..service_locator.fQCOlEZ.App\\Entity\\TypeVehicule', NULL, 'Cannot autowire service ".service_locator.fQCOlEZ": it needs an instance of "App\\Entity\\TypeVehicule" but this type has been excluded in "config/services.yaml".'],
        ], [
            'typeVehicule' => 'App\\Entity\\TypeVehicule',
        ]);
    }
}
