<?php

namespace ContainerNwY6cf3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GmX77RnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gmX77Rn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticator' => ['privates', 'App\\Security\\RegistrationAuthenticator', 'getRegistrationAuthenticatorService', true],
            'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService', true],
            'passwordEncoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
        ], [
            'authenticator' => 'App\\Security\\RegistrationAuthenticator',
            'guardHandler' => '?',
            'passwordEncoder' => '?',
        ]);

        if (isset($container->privates['.service_locator.gmX77Rn'])) {
            return $container->privates['.service_locator.gmX77Rn'];
        }

        return $container->privates['.service_locator.gmX77Rn'] = $instance;
    }
}
