<?php

namespace ContainerNwY6cf3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getColorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.N0JPHZA.App\Entity\Color' shared service.
     *
     * @return \App\Entity\Color
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.N0JPHZA": it needs an instance of "App\\Entity\\Color" but this type has been excluded in "config/services.yaml".');
    }
}
