<?php

namespace ContainerNwY6cf3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnergyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.54DAgsP.App\Entity\Energy' shared service.
     *
     * @return \App\Entity\Energy
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.54DAgsP": it needs an instance of "App\\Entity\\Energy" but this type has been excluded in "config/services.yaml".');
    }
}
