<?php

namespace ContainerNwY6cf3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3_Q3GVD.App\Entity\Options' shared service.
     *
     * @return \App\Entity\Options
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3_Q3GVD": it needs an instance of "App\\Entity\\Options" but this type has been excluded in "config/services.yaml".');
    }
}
