<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XpWMS1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xpWM_s1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xpWM_s1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'couleurRepository' => ['privates', 'App\\Repository\\CouleurRepository', 'getCouleurRepositoryService', true],
        ], [
            'couleurRepository' => 'App\\Repository\\CouleurRepository',
        ]);
    }
}
