<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__QnUFbuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..qnUFbu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..qnUFbu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticator' => ['privates', 'App\\Security\\RegistrationAuthenticator', 'getRegistrationAuthenticatorService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'guardHandler' => ['privates', '.errored.RUBc.tk', NULL, 'Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $guardHandler argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Guard\\GuardAuthenticatorHandler".'],
            'passwordEncoder' => ['privates', '.errored..YkMUNr', NULL, 'Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Core\\Encoder\\UserPasswordEncoderInterface".'],
        ], [
            'authenticator' => 'App\\Security\\RegistrationAuthenticator',
            'em' => '?',
            'guardHandler' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
