<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_APkLNc1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aPkLNc1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aPkLNc1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'couleur' => ['privates', '.errored..service_locator.aPkLNc1.App\\Entity\\Couleur', NULL, 'Cannot autowire service ".service_locator.aPkLNc1": it needs an instance of "App\\Entity\\Couleur" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'couleur' => 'App\\Entity\\Couleur',
            'em' => '?',
        ]);
    }
}
