<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z4GNeVuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z4GNeVu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Z4GNeVu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lunette' => ['privates', '.errored..service_locator.Z4GNeVu.App\\Entity\\Lunettes', NULL, 'Cannot autowire service ".service_locator.Z4GNeVu": it needs an instance of "App\\Entity\\Lunettes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lunette' => 'App\\Entity\\Lunettes',
        ]);
    }
}
