<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Em04mXhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.em04mXh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.em04mXh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lunette' => ['privates', '.errored..service_locator.em04mXh.App\\Entity\\Lunettes', NULL, 'Cannot autowire service ".service_locator.em04mXh": it needs an instance of "App\\Entity\\Lunettes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'lunette' => 'App\\Entity\\Lunettes',
        ]);
    }
}
