<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LokYg9TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lokYg9T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lokYg9T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tva' => ['privates', '.errored..service_locator.lokYg9T.App\\Entity\\Tva', NULL, 'Cannot autowire service ".service_locator.lokYg9T": it needs an instance of "App\\Entity\\Tva" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'tva' => 'App\\Entity\\Tva',
        ]);
    }
}
