<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JBDxCxfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jBDxCxf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jBDxCxf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', '.errored.FaAISPY', NULL, 'Cannot determine controller argument for "App\\Controller\\ContactController::index()": the $mailer argument is type-hinted with the non-existent class or interface: "Swift_Mailer".'],
        ], [
            'em' => '?',
            'mailer' => '?',
        ]);
    }
}
