<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTva2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lokYg9T.App\Entity\Tva' shared service.
     *
     * @return \App\Entity\Tva
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lokYg9T": it needs an instance of "App\\Entity\\Tva" but this type has been excluded in "config/services.yaml".');
    }
}
