<?php

namespace Container6glGQNH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NcvPWcS.App\Entity\Type' shared service.
     *
     * @return \App\Entity\Type
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NcvPWcS": it needs an instance of "App\\Entity\\Type" but this type has been excluded in "config/services.yaml".');
    }
}
