<?php

namespace ContainerZLeZRms;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_RUBc_TkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.RUBc.tk' shared service.
     *
     * @return \Symfony\Component\Security\Guard\GuardAuthenticatorHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $guardHandler argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\Security\\Guard\\GuardAuthenticatorHandler".');
    }
}
