<?php

namespace ContainerZLeZRms;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MUmz4CIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MUmz4CI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MUmz4CI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tva' => ['privates', '.errored..service_locator.MUmz4CI.App\\Entity\\Tva', NULL, 'Cannot autowire service ".service_locator.MUmz4CI": it needs an instance of "App\\Entity\\Tva" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tva' => 'App\\Entity\\Tva',
        ]);
    }
}
