<?php

namespace ContainerZLeZRms;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sm_VhvnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sm.vhvn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sm.vhvn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'banque' => ['privates', '.errored..service_locator.Sm.vhvn.App\\Entity\\Banque', NULL, 'Cannot autowire service ".service_locator.Sm.vhvn": it needs an instance of "App\\Entity\\Banque" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'banque' => 'App\\Entity\\Banque',
            'em' => '?',
        ]);
    }
}
