<?php

namespace ContainerZLeZRms;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouleurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZVytt8e.App\Entity\Couleur' shared service.
     *
     * @return \App\Entity\Couleur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ZVytt8e": it needs an instance of "App\\Entity\\Couleur" but this type has been excluded in "config/services.yaml".');
    }
}
