<?php

namespace ContainerZLeZRms;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLunettes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.em04mXh.App\Entity\Lunettes' shared service.
     *
     * @return \App\Entity\Lunettes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.em04mXh": it needs an instance of "App\\Entity\\Lunettes" but this type has been excluded in "config/services.yaml".');
    }
}
