<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPj8d0SL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPj8d0SL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPj8d0SL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPj8d0SL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPj8d0SL\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pj8d0SL',
    'container.build_id' => '91891acd',
    'container.build_time' => 1777967219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPj8d0SL');
