<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJdeEKcI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJdeEKcI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJdeEKcI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJdeEKcI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJdeEKcI\App_KernelDevDebugContainer([
    'container.build_hash' => 'JdeEKcI',
    'container.build_id' => 'afed6837',
    'container.build_time' => 1685645122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJdeEKcI');
